title: Website Truyện Chữ Của Tôi
description: Bộ sưu tập truyện chữ miễn phí
theme: minima

collections:
  stories:
    output: true
    permalink: /:name/  # Tạo URL dạng /rua-va-tho/ thay vì .html

defaults:
  - scope:
      path: ""
      type: stories
    values:
      layout: default  # Dùng default thay page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
