title: Website Truyện Chữ Của Tôi
description: Bộ sưu tập truyện chữ miễn phí
theme: minima

collections:
  stories:
    output: true

defaults:
  - scope:
      path: ""
      type: stories
    values:
      layout: page  # Áp layout page cho mọi truyện
  - scope:
      path: ""
      type: posts
    values:
      layout: post  # Áp layout post cho mọi chương
